# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  - 5.3
  - 5.4
  - 5.5
  - 5.6

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql
  - DB=pgsql

before_install:
  - pear channel-discover pear.pdepend.org
  - pear channel-discover pear.phpmd.org

install:
  - pear install pdepend/PHP_Depend
  - pear install phpmd/PHP_PMD
  - phpenv rehash

before_script:
  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi

script:
  - phpunit --coverage-text ./tests
  - cd build && make all

# configure notifications (email, IRC, campfire etc)
notifications:
   email: "buyer@kmd.twbbs.org"
#  irc: "irc.freenode.org#yourfavouriteroomfortravis"

