# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env: true

before_install:
#  - pyrus channel-discover pear.pdepend.org
#  - pyrus channel-discover pear.phpmd.org
  - pear channel-discover pear.pdepend.org
  - pear channel-discover pear.phpmd.org

install:
  - pyrus install pdepend/PHP_Depend
  - pyrus install phpmd/PHP_PMD
#  - pear install pdepend/PHP_Depend
#  - pear install phpmd/PHP_PMD
  - phpenv rehash

before_script: true

script:
  - phpunit --coverage-text ./tests
  - cd build && make all

# configure notifications (email, IRC, campfire etc)
notifications:
   email: "buyer@kmd.twbbs.org"
#  irc: "irc.freenode.org#yourfavouriteroomfortravis"

